version: "2"

# Local development infraestructure dependencies
services:
  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456
    tty: false
